# Generated by Django 5.1.11 on 2026-05-23 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shop Settings',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='admin', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('premium', 'Premium Plan')], default='free', max_length=20)),
                ('subscription_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('books', 'Books'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image', models.URLField(blank=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255)),
                ('cloudinary_public_ids', models.JSONField(blank=True, default=list)),
                ('available', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=False)),
                ('carousel_badge', models.CharField(choices=[('trending', 'Trending'), ('hot', 'Hot Post'), ('popular', 'Popular'), ('featured', 'Featured'), ('editors_pick', "Editor's Pick"), ('just_arrived', 'Just Arrived'), ('best_deal', 'Best Deal'), ('flash_sale', 'Flash Sale'), ('top_rated', 'Top Rated'), ('limited_stock', 'Limited Stock'), ('most_loved', 'Most Loved'), ('staff_favorite', 'Staff Favorite'), ('weekend_pick', 'Weekend Pick'), ('new_drop', 'New Drop'), ('vip_choice', 'VIP Choice'), ('fresh_finds', 'Fresh Finds'), ('mega_save', 'Mega Save'), ('premium_pick', 'Premium Pick'), ('city_choice', 'City Choice'), ('crowd_favorite', 'Crowd Favorite'), ('fast_moving', 'Fast Moving'), ('showroom_pick', 'Showroom Pick')], default='trending', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('location_link', models.URLField(blank=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_by_name', models.CharField(blank=True, max_length=255)),
                ('claimed_by_email', models.EmailField(blank=True, max_length=254)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_service_confirmed', models.BooleanField(default=False)),
                ('promo_id', models.CharField(blank=True, max_length=36)),
                ('trending_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_count', models.IntegerField(default=1)),
                ('days_count', models.IntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('upcoming', 'Upcoming'), ('expired', 'Expired'), ('archived', 'Archived'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='store.agent')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Bags',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['trending', '-created_at'], name='store_produ_trendin_9fc0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'available'], name='store_produ_categor_b51135_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['agent'], name='store_produ_agent_i_ec17e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbag',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_bag'),
        ),
    ]
